import Navbar from "./components/Navbar/Navbar";
import Modal from "./components/Modals/Modal";
import "./globals.css";
import { Nunito } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Modal isOpen disabled={false} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
